#!/system/bin/sh
#TeamMEX script for use in AOSP and dont Broke SU



[[ `grep -c corp.google.com /system/build.prop` -ge 1 ]] && /xbin/busybox run-parts /system/etc/init.d

[ -f "/system/xbin/daemonsu" ] && /system/xbin/daemonsu --auto-daemon &
